@baseUrl = http://localhost:8080

### Cadastrar aluno
POST {{baseUrl}}/alunos
Content-Type: application/json

{
  "nome": "João da Silva",
  "dataNascimento": "1995-08-05",
  "sexo": "M",
  "telefone": "1112345644",
  "celular": "119911189898",
  "email": "joao.fuzilli@email.com",
  "observacao": "Aluno iniciante",
  "endereco": "Rua das Flores",
  "numero": "123",
  "complemento": "Apartamento 169",
  "bairro": "Centro",
  "cidade": "Sao Paulo",
  "estado": "SP",
  "cep": "03155-099"
}

### Listar Alunos
GET {{baseUrl}}/alunos

### Listar Alunos com pagination
GET {{baseUrl}}/alunos?page=0&size=10&sort=nome,asc

### Buscar Aluno por ID
GET {{baseUrl}}/alunos/12

### Atualizar Aluno
PUT {{baseUrl}}/alunos/1
Content-Type: application/json

{
  "nome": "João da Silva ATUALIZADO",
  "dataNascimento": "1995-08-05",
  "sexo": "M",
  "telefone": "1112345644",
  "celular": "119911189898",
  "email": "joao@email.com",
  "observacao": "Aluno iniciante",
  "endereco": "Rua das Flores",
  "numero": "123",
  "complemento": "Apartamento 169",
  "bairro": "Centro",
  "cidade": "Sao Paulo",
  "estado": "SP",
  "cep": "03155-099"
}

### Excluir Aluno
DELETE {{baseUrl}}/alunos/1

### Cadastrar aluno
POST {{baseUrl}}/alunos
Content-Type: application/json

{
  "nome": "Maria Oliveira",
  "dataNascimento": "1997-09-21",
  "sexo": "F",
  "telefone": "1112345644",
  "celular": "119911189898",
  "email": "joao@email.com",
  "observacao": "Aluno iniciante",
  "endereco": "Rua das Flores",
  "numero": "123",
  "complemento": "Apartamento 169",
  "bairro": "Centro",
  "cidade": "Sao Paulo",
  "estado": "SP",
  "cep": "03155-099"
}

### Cadastrar aluno
POST {{baseUrl}}/alunos
Content-Type: application/json

{
  "nome": "Carlos Henrique Souza",
  "dataNascimento": "1992-03-14",
  "sexo": "M",
  "telefone": "1133445566",
  "celular": "11987654321",
  "email": "carlos.souza@email.com",
  "observacao": "Aluno intermediario",
  "endereco": "Avenida Paulista",
  "numero": "1000",
  "complemento": "Sala 45",
  "bairro": "Bela Vista",
  "cidade": "Sao Paulo",
  "estado": "SP",
  "cep": "01310-100"
}

### Cadastrar aluno INVÁLIDO
POST {{baseUrl}}/alunos
Content-Type: application/json

{
  "nome": "",
  "dataNascimento": "1997-09-21",
  "sexo": "Female",
  "telefone": "1112345644",
  "celular": "119911189898",
  "email": "joao com email.com invalid",
  "observacao": "Aluno iniciante",
  "endereco": "Rua das Flores",
  "numero": "123",
  "complemento": "Apartamento 169",
  "bairro": "Centro",
  "cidade": "Sao Paulo",
  "estado": "Saint Paul",
  "cep": "03155-099"
}

### Listar todos
GET {{baseUrl}}/alunos?page=0&size=10&sort=nome,asc

### Listar por nome
GET {{baseUrl}}/alunos?nome=maria&page=0&size=10&sort=nome,asc

### Listar por cidade
GET {{baseUrl}}/alunos?cidade=Sao Paulo&page=0&size=10&sort=nome,asc

### Listar por estado
GET {{baseUrl}}/alunos?estado=SP&page=0&size=10&sort=nome,asc


### Faturamento Mensal Report
GET {{baseUrl}}/relatorios/faturamento-mensal

### Alunos por Cidade Report
GET {{baseUrl}}/relatorios/alunos-por-cidade

### Faturas em Aberto Report
GET {{baseUrl}}/relatorios/faturas-em-aberto




