spring.application.name=academy

# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/academy
spring.datasource.username=postgres
spring.datasource.password=palmeiras
#spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Actuator
#management.endpoints.web.exposure.include=health,info

